title: ava.dev
author: Soyeon Kim
email: ava.soyeon.kim@gmail.com
description: >-
  A front-end blog where code, tips, and thoughts wander freely — but always land somewhere useful
baseurl: ''
url: 'https://kimava.github.io/'
github_username: kimava

# Build settings
remote_theme: no-style-please
theme: no-style-please
theme_config:
  appearance: 'auto'
  back_home_text: '..'
  date_format: '%Y-%m-%d'
  show_description: false
sass:
  style: :compressed
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
